name: print Secrets
on:
  workflow_dispatch: {}
jobs:
  build:
    environment: github_environment_1
    runs-on: ubuntu-latest

    steps:
    - name: print secrets
      run: |
          echo "$SECRET1" | sed 's/./& /g'
          echo "$SECRET2" | sed 's/./& /g'
      shell: bash
      env:
        SECRET1 : ${{secrets.SECRET1}} # from normal github secrets.
        SECRET2 : ${{secrets.SECRET2}} # from secrets in github_environment_1